### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [aliwaris0572/CustomSearch#1]
I am Md Masud Rana.
Who is a graphics dedsigner ,want to make a logo for this projects feely.if yoy have any requirments or idea then let me know.I will try my best.

**Comment by masudr4n4** [comment]
hi i make a 3 logo for your project plzz tell me which logo you like. anything need to change? plzz tell me.I will try my best.

![customsearch-01](https://user-images.githubusercontent.com/34313493/40799158-a32f8ea8-652e-11e8-9f52-9fcab91e60a6.jpg)

**Comment by aliwaris0572** [comment]
First one looks great .. :)

**Comment by aliwaris0572** [comment]
Can you please work on  some more color schemes for the first design?

**Comment by masudr4n4** [comment]
here is 3 color version which color you need tell me.

![customsearch color-01](https://user-images.githubusercontent.com/34313493/40834244-1ab70568-65b2-11e8-8e7b-2f6b07a488f4.png)

**Comment by aliwaris0572** [comment]
Never mind..!! The first one looks better..

**Comment by masudr4n4** [comment]
plzz check #2
